- name: PLAY-01
  hosts: web
  tasks: # this is list of the tasks.
  - name: PLAY-01
    ansible.builtin.debug: # this print command in ansible
      msg: "This is from PLAY-01 and Task-1"

- name: PLAY-02
  hosts: web
  tasks:
  - name: PLAY-02
    ansible.builtin.debug:
      msg: "This is from PLAY-02 and Task-2"