- name: nginx install and run
  hosts: web
  become: yes # it is means login with root user
  tasks:
  - name: nginx install
    ansible.builtin.package:  # if you mention package it going install any server or if you   mention any prticular server we can mention that particular package module.
      name: nginx
      state: present # it means installed the package 

  - name: nginx run
    ansible.builtin.service: # it start the service
      name: nginx
      state: started


 