- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "SHIVA"
    TIMINGS: "7AM TO 10AM"   
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg "Hi, I am learing is {{ COURSE }}, Duration is:{{ DURATION }}, Trainer is:{{ SHIVA }}, Timings is:{{ TIMINGS }}"