- name: variables to print
  hosts: web
  vars:  # play level, all tasks should be access to it
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "SHIVA"
    TIMINGS: "7AM TO 10AM"

  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}, Timings is: {{ TIMINGS }}"
