# here we can pass the variables through args

- name: variables from args
  hosts: web
  become: yes
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{ COURSE }}, Duration is: {{ DURATION }}, Timings is: {{ TIMINGS }}, Trainer is: {{ TRAINER }}"