# using this file checking variable passing through multiple ways but ansible prefering which is first

- name: variables to print
  hosts: web
  become: yes

# play level, all tasks should be access to it
  vars:  # play level, all tasks should be access to it
    COURSE: "DevOps with AWS with playlevel"
    DURATION: "120HRS"
    TRAINER: "SHIVA"
    TIMINGS: "7AM TO 10AM"

# file level variables
  # vars_files: # file level variables
  #   - vars_file.yaml

# prompt level variables
  # vars_prompt: # prompt level variables
  # - name: COURSE 
  #   prompt: please enter the course name
  # - name: DURATION
  #   prompt: please enabled the course Duration
  # - name: TIMINGS
  #   prompt: please enter the course Timings
  # - name: TRAINER
  #   prompt: please enter the Trainer name

# variable from task level
  tasks:
  - name: print the information
    vars: # variable from task level
      # COURSE: "DevOps with AWS task level"
      # DURATION: "120HRS"
      # TRAINER: "SHIVA"
      # TIMINGS: "7AM TO 10AM"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}, Timings is: {{ TIMINGS }}"



# 1. prefarance command line / args
# 2. task level
# 3. file
# 4. Prompt level
# 5. play level
# 6. inventory
# 7. role based