# using this file checking variable passing through multiple ways but ansible prefering which is first

- name: variables to print
  hosts: web
  become: yes
  vars:  # play level, all tasks should be access to it
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "SHIVA"
    TIMINGS: "7AM TO 10AM"

  vars_files: # file level variables
    - vars_file.yaml

  # vars_prompt: # prompt level variables
  # - name: COURSE
  #   prompt: please enter the course name
  # - name: DURATION
  #   prompt: please enabled the course Duration
  # - name: TIMINGS
  #   prompt: please enter the course Timings
  # - name: TRAINER
  #   prompt: please enter the Trainer name

  # tasks:
  # - name: print the information
  #   vars: # variable from task level
  #     COURSE: "DevOps with AWS"
  #     DURATION: "120HRS"
  #     TRAINER: "SHIVA"
  #     TIMINGS: "7AM TO 10AM"
  #   ansible.builtin.debug:
  #     msg: "Hi, I am learning {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}, Timings is: {{ TIMINGS }}"



# 1. variable arg
# 2. prompt
# 3. task level
# 4.