- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars_files:
    - vars.yaml
    
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances
    
    - name: print the output  # this is print the output on the terminal.
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"
    

    # here we create the private ipaddresses.

    - name: create the route53 private records # here we are creating the dns records. 
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}" # ex.mysql.daws81.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}" # in this "0" refers to index 1
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"  # this refers to list.

    - name: create the route53 public record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ zone }}" #daws81.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"
      when: item.item == "frontend"
